package com.forum.entity;

public enum NotificationType {
    NEW_COMMENT,
    QUOTE,
    MENTION,
    REACTION,
    CONVERSATION_REACTION,
    CONVERSATION_REPLY,
    CONVERSATION_QUOTE,
    CONVERSATION_MENTION,
    FOLLOWED_USER_THREAD,
    FOLLOWED_USER_POST
}
